In [1]:
import numpy as np

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
type(a)

numpy.ndarray

In [7]:
np.array([3.12, 4, 5, 7], dtype = "float32")

array([3.12, 4.  , 5.  , 7.  ], dtype=float32)

In [8]:
np.array([3.12, 4, 5, 7], dtype = "int")

array([3, 4, 5, 7])

In [9]:
np.zeros(10, dtype= int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
np.full((3,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [13]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [14]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
np.random.normal(10,4,(3,4))

array([[11.74130778, 13.4658124 , 17.19099635, 12.46332792],
       [13.06932542,  3.6723946 ,  8.31028745, 12.06379164],
       [12.40179893,  2.09457161, 11.074687  ,  4.53221482]])

In [16]:
np.random.randint(0,10,(3,4))

array([[8, 6, 8, 5],
       [0, 8, 5, 8],
       [1, 8, 8, 2]])

In [17]:
np.random.randint(10,size=10)

array([0, 3, 2, 0, 3, 6, 3, 3, 0, 8])

In [18]:
a = np.random.randint(10,size=10)

In [19]:
a.ndim

1

In [20]:
a.shape

(10,)

In [21]:
a.size

10

In [22]:
a.dtype

dtype('int32')

In [23]:
b = np.random.randint(10, size=(3,5))

In [24]:
b

array([[3, 4, 8, 5, 2],
       [3, 7, 6, 7, 1],
       [5, 5, 0, 2, 4]])

In [25]:
b.ndim

2

In [26]:
b.shape

(3, 5)

In [27]:
b.size

15

In [28]:
b.dtype

dtype('int32')

In [29]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
a = np.arange(1,10)

In [32]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a.ndim

1

In [34]:
b = a.reshape((1,9))

In [35]:
b.ndim

2

# Array birleştirme - concatenation

In [37]:
x = np.array([1,2,3])
y = np.array([4,5,6])


In [38]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [39]:
z = np.array([7,8,9])

In [40]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a = np.array([[1,2,3],
              [4,5,6]])

In [42]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [44]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array ayırma -- splitting

In [45]:
x = np.array([1,2,3,99,99,3,2,1])

In [47]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [48]:
a,b,c = np.split(x,[3,5])

In [49]:
a

array([1, 2, 3])

In [50]:
b

array([99, 99])

In [51]:
c

array([3, 2, 1])

In [53]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [56]:
ust, alt = np.vsplit(m,[2])

In [57]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [63]:
sag, sol = np.hsplit(m,[2])

In [64]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [65]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# array sıralama --> sorting

In [66]:
v = np.array([4,1,6,3,2])

In [67]:
v

array([4, 1, 6, 3, 2])

In [68]:
np.sort(v)

array([1, 2, 3, 4, 6])

In [69]:
v

array([4, 1, 6, 3, 2])

In [71]:
v.sort()

In [72]:
v

array([1, 2, 3, 4, 6])

In [74]:
m = np.random.normal(20,5, (3,3))

In [75]:
m

array([[22.31144368, 22.62792186, 12.6256315 ],
       [15.29690393, 16.47928842, 27.10703793],
       [25.30208122, 21.41143747, 18.51777693]])

In [76]:
np.sort(m, axis=1)

array([[12.6256315 , 22.31144368, 22.62792186],
       [15.29690393, 16.47928842, 27.10703793],
       [18.51777693, 21.41143747, 25.30208122]])

In [77]:
np.sort(m, axis=0)

array([[15.29690393, 16.47928842, 12.6256315 ],
       [22.31144368, 21.41143747, 18.51777693],
       [25.30208122, 22.62792186, 27.10703793]])

# index ile elemanlara erişmek

In [1]:
import numpy as np

In [3]:
a = np.random.randint(10, size=10)
a

array([7, 3, 6, 6, 5, 3, 3, 2, 4, 2])

In [4]:
a[0]

7

In [5]:
a[-1]

2

In [6]:
a[0] = 100

In [7]:
a

array([100,   3,   6,   6,   5,   3,   3,   2,   4,   2])

In [8]:
m = np.random.randint(10, size=(3,5))
m

array([[4, 3, 2, 4, 9],
       [0, 1, 4, 1, 9],
       [1, 8, 1, 3, 3]])

In [9]:
m[0,0]

4

In [10]:
m[1,1]

1

In [11]:
m[1,4]

9

In [12]:
m[1,4] = 99

In [13]:
m

array([[ 4,  3,  2,  4,  9],
       [ 0,  1,  4,  1, 99],
       [ 1,  8,  1,  3,  3]])

In [14]:
m[1,4] = 2.2

In [15]:
m

array([[4, 3, 2, 4, 9],
       [0, 1, 4, 1, 2],
       [1, 8, 1, 3, 3]])

# slicing ile elemanlara erişmek  --> array alt kümesine erişmek

In [16]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
a[0:3]

array([20, 21, 22])

In [20]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [21]:
a[1::2]

array([21, 23, 25, 27, 29])

In [22]:
a[0::3]

array([20, 23, 26, 29])

In [24]:
m = np.random.randint(10, size=(5,5))

In [25]:
m

array([[0, 0, 6, 5, 6],
       [6, 9, 6, 9, 0],
       [8, 9, 0, 8, 1],
       [7, 5, 4, 1, 3],
       [6, 4, 7, 0, 5]])

In [26]:
m[:,0]

array([0, 6, 8, 7, 6])

In [27]:
m[:,1]

array([0, 9, 9, 5, 4])

In [28]:
m[0,:]

array([0, 0, 6, 5, 6])

In [29]:
m[1,:]

array([6, 9, 6, 9, 0])

In [30]:
m[0:2 ,0:3]

array([[0, 0, 6],
       [6, 9, 6]])

In [31]:
m[:,0:2]

array([[0, 0],
       [6, 9],
       [8, 9],
       [7, 5],
       [6, 4]])

In [32]:
m

array([[0, 0, 6, 5, 6],
       [6, 9, 6, 9, 0],
       [8, 9, 0, 8, 1],
       [7, 5, 4, 1, 3],
       [6, 4, 7, 0, 5]])

In [33]:
m[1:3, 0:2]

array([[6, 9],
       [8, 9]])

# alt küme üzerinde işlem yapmak

In [34]:
a = np.random.randint(10, size=(5,5))
a

array([[0, 7, 2, 4, 3],
       [5, 4, 9, 3, 6],
       [5, 0, 8, 1, 7],
       [9, 9, 7, 5, 3],
       [1, 3, 8, 3, 5]])

In [35]:
alt_a = a[0:3, 0:2]
alt_a

array([[0, 7],
       [5, 4],
       [5, 0]])

In [37]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [38]:
alt_a

array([[99999,     7],
       [    5,   888],
       [    5,     0]])

In [39]:
a

array([[99999,     7,     2,     4,     3],
       [    5,   888,     9,     3,     6],
       [    5,     0,     8,     1,     7],
       [    9,     9,     7,     5,     3],
       [    1,     3,     8,     3,     5]])

In [40]:
m = np.random.randint(10, size=(5,5))
m

array([[2, 8, 1, 3, 0],
       [0, 2, 2, 3, 9],
       [5, 0, 0, 9, 7],
       [8, 1, 4, 0, 9],
       [7, 7, 3, 0, 2]])

In [45]:
alt_b = m[0:3 ,0:2].copy()


In [47]:
alt_b

array([[2, 8],
       [0, 2],
       [5, 0]])

In [48]:
alt_b[0:0] = 999

In [49]:
alt_b

array([[2, 8],
       [0, 2],
       [5, 0]])

In [50]:
m

array([[2, 8, 1, 3, 0],
       [0, 2, 2, 3, 9],
       [5, 0, 0, 9, 7],
       [8, 1, 4, 0, 9],
       [7, 7, 3, 0, 2]])

# fancy index ile elemanlara erişmek

In [51]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [52]:
v[1]

3

In [53]:
v[3]

9

In [54]:
[v[1],v[3], v[5]]

[3, 9, 15]

In [55]:
al_getir = [1,2,5]

In [56]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [57]:
v[al_getir]

array([ 3,  6, 15])

In [58]:
m = np.arange(9).reshape(3,3)

In [59]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [61]:
m[satir,sutun]

array([1, 5])

In [62]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
m[0, [1,2]]

array([1, 2])

In [65]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# koşullu eleman işlemleri

In [66]:
v = np.array([1,2,3,4,5])

In [67]:
v < 3

array([ True,  True, False, False, False])

In [68]:
v[v<3]

array([1, 2])

In [69]:
v[v> 3]

array([4, 5])

In [70]:
v[v>= 3]

array([3, 4, 5])

In [71]:
v[v <= 3]

array([1, 2, 3])

In [72]:
v[v == 3]

array([3])

In [73]:
v[v != 3]

array([1, 2, 4, 5])

In [74]:
v

array([1, 2, 3, 4, 5])

In [75]:
v*2

array([ 2,  4,  6,  8, 10])

In [76]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [77]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [78]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [79]:
v - 1

array([0, 1, 2, 3, 4])

In [80]:
v*4/2

array([ 2.,  4.,  6.,  8., 10.])

# **ufunc**

In [82]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [83]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [84]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [85]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [87]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [88]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [89]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [90]:
np.absolute(np.array([-3]))

array([3])

In [91]:
np.sin(360)

0.9589157234143065

In [92]:
np.cos(180)

-0.5984600690578581

In [93]:
v = np.array([1,2,3])

In [94]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [95]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [96]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [97]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\asus_\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\asus_\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >

# İstatistiksel hesaplamalar

In [98]:
v

array([1, 2, 3])

In [99]:
np.mean(v)

2.0

In [100]:
np.sum(v)

6

In [101]:
np.min(v)

1

In [102]:
np.max(v)

3

In [103]:
np.var(v)

0.6666666666666666

In [104]:
np.std(v)

0.816496580927726

In [105]:
np.corrcoef(v)

1.0

# NumPy ile iki bilinmeyenli denklem çözümü

In [106]:
a = np.array([[5,1] ,[1,3]])
b = np.array([12,10])

In [107]:
a

array([[5, 1],
       [1, 3]])

In [108]:
b

array([12, 10])

In [110]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])